### PR TITLE
Expose parametrization with alpha, not log_alpha

### PR DESCRIPTION
**Pull request by mathurinm**
@QB3 @Klopfe up to where should we hide log_alpha ?

For me, everything the basic user needs to set: alpha_max, alpha_min, alpha0, monitor.alphas.

Higher level functions, like get_val_grad, get_val_grad, get_beta_jac can keep log_alpha (the generic user does not see them)

WDYT?

### CODE REVIEW

**Comment by QB3** [comment]
> For me, everything the basic user needs to set: alpha_max, alpha_min, alpha0, monitor.alphas.

> Higher level functions, like get_val_grad, get_val_grad, get_beta_jac can keep log_alpha (the generic user does not see them)

+1, users should only see grad_search, or grid_search, not these intern functions

**Comment by QB3** [comment]
> so this becomes alpha0

all log_alpha from examples should have been removed by now :)

**Comment by QB3** [comment]
> don't know if it's the right place but I don't get why this function needs the number of points to be plotted, as 3 lines below I have to call cmap with cmap(linspace(0, 1, n_points_to_plot)

What I did is mostly taken from this gist: https://gist.github.com/jakevdp/91077b0cae40f8f8244a
Maybe there is a cleaner sol

**Comment by QB3** [comment]
Maybe we could add a parameter `ax=True` to the `discrete_cmap` function, in order to be lighter in the examples

**Comment by mathurinm** [comment]
> Maybe we could add a parameter `ax=True` to the `discrete_cmap` function, in order to be lighter in the examples

Probably there's a better solution (I think using N twice can be avoided) but we can have a look later

**Comment by QB3** [comment]
> Probably there's a better solution (I think using N twice can be avoided) but we can have a look later

Let's do this later then

**Comment by QB3** [comment]
good for you @agramfort ?

**Review by agramfort — APPROVED** [review]

**Comment by agramfort** [comment]
thx @mathurinm and @QB3 !

**Pull request merged**
