### PR TITLE
ENH: use libsvmdata to load libsvm

### PR DESCRIPTION
**Pull request by mathurinm**
@QB3 "leu" is not supported yet in libsvmadata. however it has 38 samples and I suggest you just drop it from your library instead, wdyt ?

### CODE REVIEW

**Comment by agramfort** [comment]
you need to install libsvmdata on travis and circleci

**Comment by mathurinm** [comment]
yes I forgot.

I install them directly in the `setup.py`, for me it makes life easier.

The example with leukemia needs to be updated. I think it does not make sense anyway since leu has 38 samples.

@QB3 what do you think ? Can we use news20 and subsample it instead ?

**Comment by QB3** [comment]
> yes I forgot.
> 
> I install them directly in the `setup.py`, for me it makes life easier.
> 
> The example with leukemia needs to be updated. I think it does not make sense anyway since leu has 38 samples.
> 
> @QB3 what do you think ? Can we use news20 and subsample it instead ?

I am currently writting examples with subsampled rcv1

**Comment by QB3** [comment]
LGTM, wdyt @agramfort @mathurinm

**Comment by agramfort** [comment]
thx @mathurinm and @QB3 !

**Pull request merged**
